### ISSUE TITLE
[feature request] Bash file type

### ISSUE THREAD

**Issue by Mixie-12** [OliBlade/3Cols#18]
Hi,
Would love if 3Cols supported bash.
Any plans of implementing it?

**Comment by OliBlade** [comment]
Hi Mixie,

Good news, we're in [progress](https://github.com/OliBlade/3Cols/issues/12) of switching our editor to [Monaco editor](https://github.com/microsoft/monaco-editor). This means we will soon have much greater language support including bash/ shell. I'll update this ticket when this goes live.

**Comment by OliBlade** [comment]
We rolled out this update, a little later than expected. You can now select "shell" as a language.
