### ISSUE TITLE
[feature request]  Custom font size

### ISSUE THREAD

**Issue by Mixie-12** [OliBlade/3Cols#19]
Hi,
Would love to be able to set custom/overwrite default font size for each snippet.
Some snippets I have have multiple lines of code, while others only one.
Visually it would be nicer if I could "zoom" inn the view when viewing one lined snippets.

Maybe it could be implemented by allowing custom CSS on snippets?
That would open up for a lot of custom tweaking.

**Comment by OliBlade** [comment]
Hello Mixie,

We currently have no plans to allow custom CSS or zooming. However Markdown support is [currently in testing](https://github.com/OliBlade/3Cols/issues/12) which will allow you all the custom functionality which comes with Markdown, so you could have snippets with a larger text size using that.

I will add a label on this issue to review it again at a later date
