### ISSUE TITLE
What does an organization do?

### ISSUE THREAD

**Issue by stormhillmedia** [OliBlade/3Cols#23]
The process seemed intuitive and clear. I added an organization and several email addresses. The email addresses received an invite. They signed into 3Cols with email addresses BUT no access to the board, no help, no other instructions.

... frustration

**Comment by OliBlade** [comment]
Each Board must be shared with the Organisation with the following steps:

- Create your organisation and add members
- Select the Board you would like to share (you must own this Board)
- Click the "Share Board" button in the controls on the right
- Click the "Organisations" tab in the "Manage Board Sharing" modal
- Select your "Organisation" from the dropdown and click "add"

**Comment by stormhillmedia** [comment]
OH that makes sense though not completely intuitive.
This is a really GREAT app.

Jim Camomile
Stormhill Media <http://www.stormhillmedia.com>
512-914-8458

**Comment by OliBlade** [comment]
Thanks for the feedback, we're looking at getting some docs in the future which should help clear up some of these issues
