### ISSUE TITLE
Account Gone - All boards deleted

### ISSUE THREAD

**Issue by nickfmc** [OliBlade/3Cols#30]
I haven't logged in for a while to find when logging in that everything had been removed from my account! :(

**Comment by OliBlade** [comment]
Hi Nickfmc,

This shouldn't be the case, can you give me the email address you use for the account so I can look into this for you? If you would prefer to email it to me instead please send it to support@3cols.com

**Comment by OliBlade** [comment]
I think I know the email you signed in with based on the name. However it doesn't look like this email has ever had an account associated with it. Can you confirm if it was this email you used previously?

**Comment by OliBlade** [comment]
Resolved as cache issue displaying old site version
